CREATE TABLE message_categorizer_samples
(
    message_categorizer_training_sample_id bigint GENERATED BY DEFAULT AS IDENTITY
        CONSTRAINT message_categorizer_samples_pkey
            PRIMARY KEY,
    category                               varchar(255),
    text                                   varchar(255)
);


